"""empty message

Revision ID: 15c998a175f2
Revises: e8671bf828e7
Create Date: 2022-05-30 09:39:13.862432

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '15c998a175f2'
down_revision = 'e8671bf828e7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ruta', sa.Column('colonias', sa.ARRAY(sa.String()), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ruta', 'colonias')
    # ### end Alembic commands ###
