"""empty message

Revision ID: 2c318cc64ae4
Revises: 15c998a175f2
Create Date: 2022-06-15 00:08:10.962426

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2c318cc64ae4'
down_revision = '15c998a175f2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ruta', sa.Column('colonias', sa.String(length=600), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ruta', 'colonias')
    # ### end Alembic commands ###
