"""empty message

Revision ID: b7e5d22ea591
Revises: 41de3d12ebcb
Create Date: 2022-05-30 09:37:27.433759

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b7e5d22ea591'
down_revision = '41de3d12ebcb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ruta', sa.Column('colonias', sa.ARRAY(sa.String()), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ruta', 'colonias')
    # ### end Alembic commands ###
