"""empty message

Revision ID: e8671bf828e7
Revises: b7e5d22ea591
Create Date: 2022-05-30 09:38:23.375908

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e8671bf828e7'
down_revision = 'b7e5d22ea591'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ruta', sa.Column('colonias', sa.ARRAY(sa.String()), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ruta', 'colonias')
    # ### end Alembic commands ###
